import { isJsonObject, type JsonValue } from "@agents-in-the-cloud/core";
import { Type } from "typebox";
import { Value } from "typebox/value";
import { codexNotification, type CodexNotification, type Requests } from "./protocol.ts";

export class CodexRpcError extends Error {}

/** Newline-delimited app-server RPC; replies can arrive out of request order. */
export class CodexRpc {
  private nextId = 0;
  private readonly pending = new Map<number, { resolve(value: JsonValue): void; reject(error: Error): void }>();
  private failure?: Error;
  constructor(private readonly write: (line: string) => void, private readonly notification: (notification: CodexNotification) => void) {}
  request<M extends keyof Requests>(method: M, params: Requests[M][0]): Promise<Requests[M][1]> {
    if (this.failure) return Promise.reject(this.failure);
    const id = ++this.nextId;
    const result = new Promise<JsonValue>((resolve, reject) => this.pending.set(id, { resolve, reject }));
    try { this.write(JSON.stringify({ id, method, params }) + "\n"); }
    catch (error) { this.fail(error instanceof Error ? error : new Error(String(error))); }
    // SAFETY: Responses are generated by the pinned Codex app-server protocol.
    return result as Promise<Requests[M][1]>;
  }
  notify(method: string) { this.write(JSON.stringify({ method }) + "\n"); }
  receive(line: string) {
    const message: unknown = JSON.parse(line);
    if (!isJsonObject(message)) throw new Error("Invalid Codex RPC message");
    if (Value.Check(Type.String(), message.method)) {
      if (message.id !== undefined) {
        // Approval policy is never; unsupported interactive tools must fail visibly,
        // not leave Codex waiting indefinitely for a client response.
        this.write(JSON.stringify({ id: message.id, error: { code: -32601, message: `AgentsInTheCloud does not support ${message.method} yet` } }) + "\n");
        this.notification({ method: "client/unsupportedRequest", params: { method: message.method } });
      } else {
        const notification = codexNotification(message.method, message.params ?? null);
        if (notification) this.notification(notification);
      }
      return;
    }
    if (!Value.Check(Type.Number(), message.id)) throw new Error("Invalid Codex RPC response ID");
    const pending = this.pending.get(message.id);
    if (!pending) throw new Error(`Unknown Codex RPC response: ${message.id}`);
    if (message.error !== undefined) {
      if (!isJsonObject(message.error) || !Value.Check(Type.String(), message.error.message)) throw new Error("Invalid Codex RPC error");
      this.pending.delete(message.id);
      pending.reject(new CodexRpcError(message.error.message));
    } else {
      if (!("result" in message)) throw new Error("Missing Codex RPC result");
      this.pending.delete(message.id);
      pending.resolve(message.result);
    }
  }
  fail(error: Error) {
    this.failure = error;
    for (const pending of this.pending.values()) pending.reject(error);
    this.pending.clear();
  }
}
