import { mkdtemp, readFile, writeFile, copyFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, dirname, resolve, relative } from "node:path";
import { codexVersion } from "../src/server/protocol.ts";

const temporary = await mkdtemp(join(tmpdir(), "codex-app-server-protocol-"));
const generated = join(temporary, "generated");
const destination = resolve(import.meta.dir, "../src/protocol.ts");
const roots = [
  "InitializeParams", "InitializeResponse", "v2/ThreadStartParams", "v2/ThreadStartResponse",
  "v2/ThreadResumeParams", "v2/ThreadResumeResponse", "v2/TurnStartParams",
  "v2/TurnStartResponse", "v2/TurnSteerParams", "v2/TurnSteerResponse",
  "v2/TurnInterruptParams", "v2/TurnInterruptResponse", "v2/ThreadReadParams", "v2/ThreadReadResponse", "v2/ModelListParams",
  "v2/ModelListResponse", "v2/ThreadTokenUsageUpdatedNotification",
  "v2/ItemStartedNotification", "v2/ItemCompletedNotification",
  "v2/TurnStartedNotification", "v2/TurnCompletedNotification",
  "v2/AgentMessageDeltaNotification", "v2/PlanDeltaNotification", "v2/ErrorNotification", "v2/ReasoningSummaryTextDeltaNotification",
  "v2/CommandExecutionOutputDeltaNotification",
  ...["ThreadSettingsUpdate", "ThreadCompactStart", "ReviewStart", "ThreadFork", "ThreadList", "ThreadGoalGet", "ThreadGoalSet", "ThreadGoalClear", "SkillsList", "ListMcpServerStatus", "HooksList", "PluginList", "PluginInstall", "PluginUninstall", "SkillsConfigWrite", "AppsList"].flatMap(name => [`v2/${name}Params`, `v2/${name}Response`]),
  "v2/ConfigValueWriteParams", "v2/ConfigWriteResponse",
];
try {
  const install = Bun.spawn(["npm", "install", "--prefix", temporary, "--no-audit", "--no-fund", `@openai/codex@${codexVersion}`], { stdin: "ignore", stdout: "inherit", stderr: "inherit" });
  if (await install.exited !== 0) throw new Error("Could not install the pinned Codex generator");
  const generator = Bun.spawn([join(temporary, "node_modules/.bin/codex"), "app-server", "generate-ts", "--out", generated], { stdin: "ignore", stdout: "inherit", stderr: "inherit" });
  if (await generator.exited !== 0) throw new Error("Could not generate the Codex protocol");
  // Settings updates are experimental in this pin. Keep stable shapes for all
  // existing operations and import only this method and its extra dependency.
  const experimental = join(temporary, "experimental");
  const experimentalGenerator = Bun.spawn([join(temporary, "node_modules/.bin/codex"), "app-server", "generate-ts", "--experimental", "--out", experimental], { stdin: "ignore", stdout: "inherit", stderr: "inherit" });
  if (await experimentalGenerator.exited !== 0) throw new Error("Could not generate the experimental Codex protocol");
  for (const path of ["v2/ThreadSettingsUpdateParams.ts", "v2/ThreadSettingsUpdateResponse.ts", "MultiAgentMode.ts"]) {
    await copyFile(join(experimental, path), join(generated, path));
  }
  const sources = new Map<string, string>();
  async function collect(path: string): Promise<void> {
    if (sources.has(path)) return;
    const source = await readFile(path, "utf8");
    sources.set(path, source);
    for (const match of source.matchAll(/from "([^"]+)"/g)) await collect(resolve(dirname(path), `${match[1]}.ts`));
  }
  for (const root of roots) await collect(join(generated, `${root}.ts`));
  const declarations = new Set<string>();
  const sections = [...sources].sort(([a], [b]) => a.localeCompare(b)).map(([path, source]) => {
    for (const match of source.matchAll(/^export type (\w+)/gm)) {
      if (declarations.has(match[1]!)) throw new Error(`Duplicate protocol type: ${match[1]}`);
      declarations.add(match[1]!);
    }
    const body = source
      .replace(/^import type .*;\r?\n/gm, "")
      .replace(/^\/\/ GENERATED CODE! DO NOT MODIFY BY HAND!\r?\n/gm, "")
      .replace(/^\/\/ This file was generated by \[ts-rs\].*\r?\n/gm, "")
      .trim();
    return `// Source: ${relative(generated, path)}\n${body}`;
  });
  await writeFile(destination, `// GENERATED CODE! DO NOT MODIFY BY HAND!\n// Codex ${codexVersion}; regenerate with bun packages/codex-app-server-agent/scripts/generate-protocol.ts\n\n${sections.join("\n\n")}\n`);
  console.log(`Generated ${sources.size} protocol types in ${destination} for Codex ${codexVersion}`);
} finally { await rm(temporary, { recursive: true, force: true }); }
