import type { Context } from "@earendil-works/chord";
import type { ImageContent, Models, TextContent } from "@earendil-works/pi-ai";
import { formatDimensionNote, resizeImage } from "@earendil-works/pi-coding-agent";
import type { Conversation, InputSubmissionDraft } from "@earendil-works/pi-durable";
import { expandWorkspaceSkillCommand } from "./skills.ts";

export type DurableInput = {
  /** Generated by the caller before HTTP admission, and retained for retries. */
  requestId: string;
  text: string;
  attachmentNotes?: readonly string[];
  images?: readonly ImageContent[];
  whenBusy?: InputSubmissionDraft["whenBusy"];
};

/** Prepare outside journal transactions; Durable owns admission and steering deduplication. */
export async function submitDurableInput(
  conversation: Conversation,
  workspaceId: string,
  models: Pick<Models, "getModel">,
  input: DurableInput,
  context: Context,
  expand: typeof expandWorkspaceSkillCommand = expandWorkspaceSkillCommand,
  beforeAdmit: () => void = () => {},
) {
  if (!input.requestId.trim()) throw new Error("A request ID is required for durable input");
  const text = [input.text.trim(), ...(input.attachmentNotes ?? [])].filter(Boolean).join("\n\n");
  if (!text && !input.images?.length) throw new Error("A message or image is required");
  const agent = await conversation.agent(context);
  const model = agent.model ? models.getModel(agent.model.provider, agent.model.modelId) : undefined;
  if (agent.model && !model) throw new Error(`Model not found: ${agent.model.provider}/${agent.model.modelId}`);
  const content: (TextContent | ImageContent)[] = [];
  if (text) content.push({ type: "text", text: await expand(workspaceId, text) });
  for (const image of input.images ?? []) {
    const resized = await resizeImage(Buffer.from(image.data, "base64"), image.mimeType, model?.inputLimits?.images?.resize);
    if (!resized) throw new Error("The attached image could not be resized to fit the model's image limits");
    content.push({ type: "image", data: resized.data, mimeType: resized.mimeType });
    const note = formatDimensionNote(resized);
    if (note) content.push({ type: "text", text: note });
  }
  if (input.images?.length && model && !model.input.includes("image")) {
    content.push({ type: "text", text: "Current model does not support images. Attached images are retained in history but omitted from this request." });
  }
  beforeAdmit();
  return conversation.submit({ type: "input", requestId: input.requestId, content, whenBusy: input.whenBusy ?? "steer" }, context);
}
