import type { JsonObject } from "@agents-in-the-cloud/core";
const workspaceId = { name: "id", in: "path", required: true, schema: { type: "string" } };
const agent = { name: "agent", in: "query", schema: { type: "string" } };
const errorResponse = { description: "Not found" };
const jsonAndHtmlResponse = (description: string, schema: JsonObject) => ({ "200": { description, content: { "application/json": { schema }, "text/html": { schema: { type: "string" } } } } });
export const subagentsOpenApiPaths = {
"/workspaces/{id}/subagents": { get: { summary: "Inspect a selected Agent's Subagents tree and plaintext communication ledger", parameters: [workspaceId, agent, { name: "open", in: "query", required: false, schema: { type: "array", items: { type: "string" } } }, { name: "reveal", in: "query", required: false, schema: { type: "string" } }], responses: jsonAndHtmlResponse("Subagents, lifecycle states, messages and results; HTML contains folding Subagent transcript mounts", { type: "object", required: ["parent", "agents", "messages"], properties: { parent: { type: "object", required: ["id", "title"], properties: { id: { type: "string" }, title: { type: "string" } } }, agents: { type: "array", items: { type: "object" } }, messages: { type: "array", items: { type: "object" } } } }) } },
"/workspaces/{id}/subagents/reveal": { get: { summary: "Navigate to a message source or recipient", parameters: [workspaceId, { name: "child", in: "query", required: true, schema: { type: "string" } }, { name: "message", in: "query", required: true, schema: { type: "string" } }], responses: { "303": { description: "Redirect to the root Agent transcript or expanded Subagent" }, "404": errorResponse } }, post: { summary: "Reveal a message source or destination in its root Agent or Subagent transcript", parameters: [workspaceId], requestBody: { required: true, content: { "application/x-www-form-urlencoded": { schema: { type: "object", required: ["child", "message"], properties: { child: { type: "string" }, message: { type: "string" } } } } } }, responses: { "303": { description: "Redirect to the root transcript or an expanded child" }, "404": errorResponse } } },
} satisfies Record<string, JsonObject>;
